
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

 
 
public class TelaVisualizar extends javax.swing.JFrame {

    public static ArrayList<Cadastro> banco = new ArrayList();
    public static int cont = 0;
    private TelaCadastro tc;
    public static Cadastro cad = new Cadastro(null, null, null, null, 0, 0, null);
    public TelaVisualizar(ArrayList<Cadastro> x) {
        super("Visualizar cadastros");
        initComponents();
        this.banco = x;
        
        this.jTextFieldBuscar.setText("");
        jLabel9.setText("");
        Atualiza();
    }
    
    public void Atualiza(){
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        if(banco.size()<=0){
            this.jTextNome.setText("Nada a exibir");
            this.jTextEndereco.setText("Nada a exibir");
            this.jTextCidade.setText("Nada a exibir");
            this.jTextDataNasc.setText("Nada a exibir");
            this.jTextAltura.setText("Nada a exibir");
            this.jTextNumero.setText("Nada a exibir");
            this.jLabelFoto.setText("Nada a exibir");
            this.jLabel10.setText("");
            this.jTextEstado.setText("Nada a exibir");
        } else{
        
            if(cont > banco.size()-1)
                cont = banco.size()-1;

            this.jTextNome.setText(this.banco.get(cont).getNome());
            this.jTextEndereco.setText(this.banco.get(cont).getEndereco());
            this.jTextCidade.setText(this.banco.get(cont).getCidade());
            this.jTextDataNasc.setText(String.valueOf(formato.format(this.banco.get(cont).getDataNasc())));
            this.jTextAltura.setText(String.valueOf(this.banco.get(cont).getAltura()));
            this.jTextNumero.setText(String.valueOf(this.banco.get(cont).getNumero()));
            this.jLabelFoto.setIcon(this.banco.get(cont).getFoto());
            //o erro em nao mostrar a foto era porque tinha colocado setText ao inves de setIcon
            //this.jLabel10.setText(this.banco.get(cont).getNome()+" tem "+String.valueOf(this.banco.get(cont).getIdade())+" anos");
            this.jLabel10.setText(String.valueOf(this.banco.get(cont).getIdade())+" anos");
            this.jTextEstado.setText(this.banco.get(cont).getEstado().getNome());

        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCidade = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextEstado = new javax.swing.JTextField();
        jTextDataNasc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bttProximo = new javax.swing.JButton();
        jTextAltura = new javax.swing.JTextField();
        bttSair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bttAnterior = new javax.swing.JButton();
        jTextEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setText("FOTO");

        jLabel7.setText("Cidade:");

        jLabel2.setText("Nome completo:");

        jLabel8.setText("Estado:");

        jLabel3.setText("Data de Nascimento:");

        jLabel4.setText("Altura:");

        bttProximo.setText("Próximo");
        bttProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttProximoActionPerformed(evt);
            }
        });

        bttSair.setText("Sair");
        bttSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSairActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço:");

        bttAnterior.setText("Anterior");
        bttAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAnteriorActionPerformed(evt);
            }
        });

        jLabel6.setText("Número:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1txtAreaMouseClick(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jTextFieldBuscar.setText("jTextField1");
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                soltarTecla(evt);
            }
        });

        jLabel1.setText("Buscar");

        jLabel9.setText("jLabel9");

        jLabel10.setText("jLabel10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttAnterior)
                        .addGap(53, 53, 53)
                        .addComponent(bttSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(bttProximo))
                    .addComponent(jTextCidade)
                    .addComponent(jTextNumero)
                    .addComponent(jTextEndereco)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(jTextAltura)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10))))
                    .addComponent(jTextEstado, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldBuscar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttProximo)
                            .addComponent(bttSair)
                            .addComponent(bttAnterior))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(28, 28, 28))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttProximoActionPerformed
        cont++;
        if(cont > banco.size()-1)
           cont = 0;
        Atualiza();
    }//GEN-LAST:event_bttProximoActionPerformed

    private void bttSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSairActionPerformed

        this.tc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttSairActionPerformed

    private void bttAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAnteriorActionPerformed
        cont--;
        if(cont < 0)
            cont = banco.size()-1;
        Atualiza();
    }//GEN-LAST:event_bttAnteriorActionPerformed

    private void jTextArea1txtAreaMouseClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1txtAreaMouseClick
        try {
            // descubro qual linha foi clicada
            int linha = this.jTextArea1.getLineOfOffset(jTextArea1.getCaretPosition());
            // defino o inicio do texto dessa linha
            int inicio = jTextArea1.getLineStartOffset(linha);
            // defino o final da linha
            int fim = jTextArea1.getLineEndOffset(linha);

            //gero um string a partir a linha que foi clicada
            String s = jTextArea1.getDocument().getText(inicio, fim-inicio-1);
            //this.jTextFieldBuscar.setText(s);

            this.jTextArea1.select(inicio, fim-1);
            for (int i = 0; i < banco.size(); i++) {
                if(banco.get(i).getNome().toLowerCase().contains(s.toLowerCase())){
                    cont = i;
                    this.Atualiza();
                }
            }

        } catch (BadLocationException ex) {
            Logger.getLogger(TelaVisualizar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextArea1txtAreaMouseClick

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
   
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void soltarTecla(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_soltarTecla
        this.jTextArea1.setText("");
        String s = this.jTextFieldBuscar.getText();

        for (int i = 0; i < banco.size(); i++) {
            if(banco.get(i).getNome().toLowerCase().contains(s.toLowerCase())){
                this.jTextArea1.append(banco.get(i).getNome()+"\n");
            }
            
        }
        this.jLabel9.setText(String.valueOf(this.jTextArea1.getLineCount()-1)+" registros encontrados");

    }//GEN-LAST:event_soltarTecla

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizar(banco).setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAnterior;
    private javax.swing.JButton bttProximo;
    private javax.swing.JButton bttSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAltura;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextCidade;
    private javax.swing.JTextField jTextDataNasc;
    private javax.swing.JTextField jTextEndereco;
    private javax.swing.JTextField jTextEstado;
    private javax.swing.JTextField jTextFieldBuscar;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextNumero;
    // End of variables declaration//GEN-END:variables

    void setTelaAuxiliar(TelaCadastro tc) {
        this.tc = tc;
    }
}
